package com.perceptiva.test;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class firstDesign extends VerticalLayout {
	protected HorizontalLayout hl;
	protected Label lblNombre;
	protected Button btn1;
	protected NativeButton btnWolverine;
	protected NativeButton btnXMen;
	protected NativeButton btnSuperman;
	protected NativeButton btnRobocosa;

	public firstDesign() {
		Design.read(this);
	}
}
